### PR TITLE
Desktop version

### PR DESCRIPTION
**Pull request by kwesiObuobi**
- Designed the desktop version of the portfolio site
- Parsed a Figma design to create the UI
- Used the correct GitHub flow
- Used media queries to make the website display correctly on desktop screens
- Used grid and flexbox to lay out elements on the page

### CODE REVIEW

**Review by ShadyShawkat — APPROVED** [review]
## Hi @kwesiObuobi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kwesiObuobi** [comment]
Thank you @ShadyShawkat 😊.
You've approved me for the second time. That's awesome. 😆 
Can I connect and follow you on Linkedin? 😊

**Comment by ShadyShawkat** [comment]
> Thank you @ShadyShawkat 😊. You've approved me for the second time. That's awesome. 😆 Can I connect and follow you on Linkedin? 😊

That would be great @kwesiObuobi, I'm glad I could help. 🙌🏻

**Comment by kwesiObuobi** [comment]
Great! Great!! Thank you @ShadyShawkat 😊

**Pull request merged**
